
/*paginated SQL query*/
SELECT c.C_CUSTOMER_ID, c.C_FIRST_NAME, 
c.C_LAST_NAME, c.C_BIRTH_DAY, c.C_BIRTH_MONTH, 
c.C_BIRTH_YEAR, c.C_EMAIL_ADDRESS, a.CA_STREET_NAME,
a.CA_STREET_NUMBER, a.CA_CITY, a.CA_STATE, a.CA_COUNTRY
FROM CUSTOMER c INNER JOIN 
     CUSTOMER_ADDRESS a ON a.ca_address_id = C.C_CUSTOMER_ID
LIMIT 10 OFFSET 0;


/*CUSTOMERID query*/
SELECT c.C_CUSTOMER_ID, c.C_FIRST_NAME, 
c.C_LAST_NAME, c.C_BIRTH_DAY, c.C_BIRTH_MONTH, 
c.C_BIRTH_YEAR, c.C_EMAIL_ADDRESS, a.CA_STREET_NAME,
a.CA_STREET_NUMBER, a.CA_CITY, a.CA_STATE, a.CA_COUNTRY
FROM CUSTOMER c INNER JOIN 
     CUSTOMER_ADDRESS a ON a.ca_address_id = C.C_CUSTOMER_ID
WHERE c.C_CUSTOMER_ID = "";